server:
  port: 8900

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cantata
    username: root
    password: mariadb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cantata.tradetalent.domain
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      cantata:
        tradetalent: DEBUG
    org:
      apache:
        ibatis: DEBUG

file:
  upload:
    location: ${user.home}/trade-talent/uploads/

jwt:
  secret-key: hpiQfYdtu+34loYL7+DBJNJ0mpPGOAl5HQqCjmbLLaQ= # 토큰 발급시와 토큰 위조 검사시 사용할 서명
  access-token-validity-time: 3600000  # 1시간
  refresh-token-validity-time: 604800000 # 7일